sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - slack: awethemes-team:lTIE3YWB1BNdxPtJoJBdIemh
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - bigchange-beta

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.7.5 WP_MULTISITE=0
  - WP_VERSION=4.6.6 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script:
  - phpunit
