sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.6.6 WP_MULTISITE=0

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Allow MySQL to finish starting
  - while ! mysqladmin ping --silent; do sleep 5; echo "Waiting for MySQL..."; done

before_script:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --no-interaction --prefer-source --no-suggest
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - slack: awethemes-team:lTIE3YWB1BNdxPtJoJBdIemh
    on_success: never
    on_failure: change
