<?php

return [ // @codingStandardsIgnoreStart
	'required'       => esc_html__( 'is required', 'awebooking' ),
	'equals'         => esc_html__( "must be the same as '%s'", 'awebooking' ),
	'different'      => esc_html__( "must be different than '%s'", 'awebooking' ),
	'accepted'       => esc_html__( 'must be accepted', 'awebooking' ),
	'numeric'        => esc_html__( 'must be numeric', 'awebooking' ),
	'integer'        => esc_html__( 'must be an integer', 'awebooking' ),
	'length'         => esc_html__( 'must be %d characters long', 'awebooking' ),
	'min'            => esc_html__( 'must be at least %s', 'awebooking' ),
	'max'            => esc_html__( 'must be no more than %s', 'awebooking' ),
	'in'             => esc_html__( 'contains invalid value', 'awebooking' ),
	'notIn'          => esc_html__( 'contains invalid value', 'awebooking' ),
	'ip'             => esc_html__( 'is not a valid IP address', 'awebooking' ),
	'ipv4'           => esc_html__( 'is not a valid IPv4 address', 'awebooking' ),
	'ipv6'           => esc_html__( 'is not a valid IPv6 address', 'awebooking' ),
	'email'          => esc_html__( 'is not a valid email address', 'awebooking' ),
	'url'            => esc_html__( 'is not a valid URL', 'awebooking' ),
	'urlActive'      => esc_html__( 'must be an active domain', 'awebooking' ),
	'alpha'          => esc_html__( 'must contain only letters a-z', 'awebooking' ),
	'alphaNum'       => esc_html__( 'must contain only letters a-z and/or numbers 0-9', 'awebooking' ),
	'slug'           => esc_html__( 'must contain only letters a-z, numbers 0-9, dashes and underscores', 'awebooking' ),
	'regex'          => esc_html__( 'contains invalid characters', 'awebooking' ),
	'date'           => esc_html__( 'is not a valid date', 'awebooking' ),
	'dateFormat'     => esc_html__( "must be date with format '%s'", 'awebooking' ),
	'dateBefore'     => esc_html__( "must be date before '%s'", 'awebooking' ),
	'dateAfter'      => esc_html__( "must be date after '%s'", 'awebooking' ),
	'contains'       => esc_html__( 'must contain %s', 'awebooking' ),
	'boolean'        => esc_html__( 'must be a boolean', 'awebooking' ),
	'lengthBetween'  => esc_html__( 'must be between %d and %d characters', 'awebooking' ),
	'creditCard'     => esc_html__( 'must be a valid credit card number', 'awebooking' ),
	'lengthMin'      => esc_html__( 'must be at least %d characters long', 'awebooking' ),
	'lengthMax'      => esc_html__( 'must not exceed %d characters', 'awebooking' ),
	'instanceOf'     => esc_html__( "must be an instance of '%s'", 'awebooking' ),
	'containsUnique' => esc_html__( 'must contain unique elements only', 'awebooking' ),
	'subset'         => esc_html__( 'contains an item that is not in the list', 'awebooking' ),
]; // @codingStandardsIgnoreEnd
